"""nullable text

Revision ID: 6481ddf5a573
Revises: d9291d8fdca6
Create Date: 2020-02-01 21:34:37.671749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6481ddf5a573'
down_revision = 'd9291d8fdca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
