"""vectors

Revision ID: d4b4a10780c9
Revises: 
Create Date: 2020-02-01 19:38:49.373452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b4a10780c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition', sa.String(length=64), nullable=True),
    sa.Column('topics', sa.String(length=120), nullable=True),
    sa.Column('subtopics', sa.String(length=120), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_edition'), 'new', ['edition'], unique=False)
    op.create_index(op.f('ix_new_subtitle'), 'new', ['subtitle'], unique=False)
    op.create_index(op.f('ix_new_subtopics'), 'new', ['subtopics'], unique=False)
    op.create_index(op.f('ix_new_title'), 'new', ['title'], unique=False)
    op.create_index(op.f('ix_new_topics'), 'new', ['topics'], unique=False)
    op.create_table('vector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('new_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['new_id'], ['new.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector')
    op.drop_index(op.f('ix_new_topics'), table_name='new')
    op.drop_index(op.f('ix_new_title'), table_name='new')
    op.drop_index(op.f('ix_new_subtopics'), table_name='new')
    op.drop_index(op.f('ix_new_subtitle'), table_name='new')
    op.drop_index(op.f('ix_new_edition'), table_name='new')
    op.drop_table('new')
    # ### end Alembic commands ###
