"""empty message

Revision ID: d9291d8fdca6
Revises: d4b4a10780c9
Create Date: 2020-02-01 19:48:12.237193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9291d8fdca6'
down_revision = 'd4b4a10780c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.Text(), nullable=True),
    sa.Column('new_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['new_id'], ['new.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector')
    # ### end Alembic commands ###
